import type { SectionDef } from "../field-types";

const CONTAINER_PATH = "TaskTemplate.ContainerSpec";

export const containerSection: SectionDef = {
	id: "container",
	title: "Container spec",
	path: CONTAINER_PATH,
	summary:
		"What each task actually runs: image, command, environment and working directory.",
	details: [
		"`ContainerSpec`, `PluginSpec` and `NetworkAttachmentSpec` are mutually exclusive — a normal service always uses `ContainerSpec`.",
		"Changing `Image` here is what triggers a rolling redeploy. Swarm resolves the tag to a digest at update time and pins that digest onto every task, so pushing a new image to the same tag does *not* redeploy anything by itself.",
	],
	fields: [
		{
			id: "image",
			path: `${CONTAINER_PATH}.Image`,
			key: "Image",
			type: "text",
			title: "Image",
			summary: "The image reference each task runs.",
			details: [
				"Give a tag (`nginx:1.27`) or, better for reproducibility, a digest (`nginx@sha256:...`). Managers resolve tags to a digest once and store the pinned reference in the running spec, which is why `docker service inspect` shows a longer string than you sent.",
				"Pass `--with-registry-auth` (CLI) or the `X-Registry-Auth` header (API) when the image lives in a private registry, otherwise worker nodes cannot pull it.",
			],
			placeholder: "nginx:1.27-alpine",
			cli: "docker service update --image nginx:1.27-alpine api-gateway",
			compose: "services.<key>.image",
			caution:
				"Re-pushing the same tag does not restart tasks. Use ForceUpdate or a digest to guarantee a redeploy.",
		},
		{
			id: "command",
			path: `${CONTAINER_PATH}.Command`,
			key: "Command",
			type: "lines",
			title: "Command (entrypoint override)",
			summary: "Replaces the image's ENTRYPOINT. One argv element per line.",
			details: [
				"This is argv, not a shell line: `sh -c 'foo | bar'` must be entered as three lines — `sh`, `-c`, `foo | bar`.",
				"Leave it off to keep whatever the image declares.",
			],
			placeholder: "nginx\n-g\ndaemon off;",
			cli: "docker service create --entrypoint",
			compose: "services.<key>.entrypoint",
		},
		{
			id: "args",
			path: `${CONTAINER_PATH}.Args`,
			key: "Args",
			type: "lines",
			title: "Args (command arguments)",
			summary: "Arguments appended after the entrypoint. One per line.",
			details: [
				"`Args` maps to the image's CMD. It is replaced wholesale on update — sending an empty array clears the arguments rather than leaving them alone.",
			],
			placeholder: "--config\n/etc/app/config.yaml",
			cli: "docker service update --args '--config /etc/app/config.yaml'",
			compose: "services.<key>.command",
		},
		{
			id: "env",
			path: `${CONTAINER_PATH}.Env`,
			key: "Env",
			type: "lines",
			title: "Environment variables",
			summary: "A list of `VAR=value` strings injected into every task.",
			details: [
				"Note the shape: this is an *array of strings*, not an object. `LOG_LEVEL=debug` is one element.",
				"Env is replaced as a whole on update, so a partial spec that omits `Env` wipes every variable. This is the single most common way to break a service with a hand-written update body.",
			],
			placeholder: "NODE_ENV=production\nLOG_LEVEL=info",
			cli: "docker service update --env-add LOG_LEVEL=info",
			compose: "services.<key>.environment",
			lineHint: "kv",
			caution:
				"Never put secrets here — env is readable by anyone who can call `docker service inspect`. Use Secrets instead.",
		},
		{
			id: "container-labels",
			path: `${CONTAINER_PATH}.Labels`,
			key: "Labels",
			type: "mapLines",
			title: "Container labels",
			summary:
				"Key/value metadata stamped onto every container of the service.",
			details: [
				"Distinct from service labels: these land on the containers, so `docker ps --filter label=...` on a worker node can see them.",
			],
			placeholder: "com.example.tier=frontend",
			cli: "docker service update --container-label-add com.example.tier=frontend",
			compose: "services.<key>.labels",
			lineHint: "kv",
		},
		{
			id: "workdir",
			path: `${CONTAINER_PATH}.Dir`,
			key: "Dir",
			type: "text",
			title: "Working directory",
			summary: "The working directory commands run in.",
			details: [
				"Overrides the image's WORKDIR. The path is not created for you — it must exist in the image or on a mounted volume.",
			],
			placeholder: "/srv/app",
			cli: "docker service update --workdir /srv/app",
			compose: "services.<key>.working_dir",
		},
		{
			id: "user",
			path: `${CONTAINER_PATH}.User`,
			key: "User",
			type: "text",
			title: "User",
			summary: "The user (and optionally group) the process runs as.",
			details: [
				"Accepts `name`, `uid`, `name:group` or `uid:gid`. Numeric ids are safer because they do not depend on /etc/passwd inside the image.",
			],
			placeholder: "1000:1000",
			cli: "docker service update --user 1000:1000",
			compose: "services.<key>.user",
		},
		{
			id: "groups",
			path: `${CONTAINER_PATH}.Groups`,
			key: "Groups",
			type: "lines",
			title: "Supplementary groups",
			summary: "Additional groups the container process joins. One per line.",
			details: [
				"Useful when a mounted host device or socket is owned by a group that the primary user is not in.",
			],
			placeholder: "docker\n2000",
			cli: "docker service update --group-add docker",
			compose: "services.<key>.group_add",
		},
		{
			id: "hostname",
			path: `${CONTAINER_PATH}.Hostname`,
			key: "Hostname",
			type: "text",
			title: "Hostname",
			summary: "The hostname each container reports, as an RFC 1123 name.",
			details: [
				"Swarm expands the templating placeholders `{{.Service.Name}}`, `{{.Task.Slot}}` and `{{.Node.Hostname}}` here, which is how you give stateful replicas stable identities.",
			],
			placeholder: "{{.Service.Name}}-{{.Task.Slot}}",
			cli: "docker service update --hostname '{{.Service.Name}}-{{.Task.Slot}}'",
			compose: "services.<key>.hostname",
		},
		{
			id: "hosts",
			path: `${CONTAINER_PATH}.Hosts`,
			key: "Hosts",
			type: "lines",
			title: "Extra hosts",
			summary:
				"Additional /etc/hosts entries, in `IP hostname [aliases...]` form.",
			details: [
				"Watch the ordering: the API wants `10.0.0.5 legacy-db`, i.e. IP first — the opposite of the CLI's `--host legacy-db:10.0.0.5`.",
			],
			placeholder: "10.0.0.5 legacy-db legacy-db.internal",
			cli: "docker service update --host-add legacy-db:10.0.0.5",
			compose: "services.<key>.extra_hosts",
			lineHint: "host",
		},
		{
			id: "stop-signal",
			path: `${CONTAINER_PATH}.StopSignal`,
			key: "StopSignal",
			type: "text",
			title: "Stop signal",
			summary: "The signal sent to ask the container to shut down.",
			details: [
				"Defaults to SIGTERM. Some servers (nginx before 1.19, for instance) want SIGQUIT for a graceful drain.",
			],
			placeholder: "SIGQUIT",
			cli: "docker service update --stop-signal SIGQUIT",
			compose: "services.<key>.stop_signal",
		},
		{
			id: "stop-grace-period",
			path: `${CONTAINER_PATH}.StopGracePeriod`,
			key: "StopGracePeriod",
			type: "duration",
			title: "Stop grace period",
			summary:
				"How long to wait after the stop signal before the container is killed.",
			details: [
				"This is the budget your process has to finish in-flight requests. If it is shorter than your longest request, rolling updates will drop connections.",
				"Docker's own default is 10 seconds, which is usually too short for anything serving long-lived HTTP or WebSocket traffic.",
			],
			defaultUnit: "s",
			placeholder: "30",
			cli: "docker service update --stop-grace-period 30s",
			compose: "services.<key>.stop_grace_period",
		},
	],
};

export const runtimeSection: SectionDef = {
	id: "runtime",
	title: "Runtime & security",
	path: CONTAINER_PATH,
	summary:
		"Kernel-level switches: read-only root, capabilities, sysctls and ulimits.",
	details: [
		"Most of these are hardening knobs. They are cheap to set and are the first thing a security review asks about.",
	],
	fields: [
		{
			id: "read-only",
			path: `${CONTAINER_PATH}.ReadOnly`,
			key: "ReadOnly",
			type: "boolean",
			title: "Read-only root filesystem",
			summary: "Mounts the container's root filesystem read-only.",
			details: [
				"A strong, low-effort hardening win. Pair it with a tmpfs mount for `/tmp` and any cache directory the process writes to, or it will crash on startup.",
			],
			cli: "docker service update --read-only",
			compose: "services.<key>.read_only",
		},
		{
			id: "init",
			path: `${CONTAINER_PATH}.Init`,
			key: "Init",
			type: "boolean",
			title: "Run an init process",
			summary: "Runs a tiny init as PID 1 to forward signals and reap zombies.",
			details: [
				"Turn this on whenever the image's entrypoint is a shell script or a language runtime that does not reap children. Without it, `StopSignal` may never reach your process and every stop degrades into a SIGKILL after the grace period.",
			],
			cli: "docker service update --init",
			compose: "services.<key>.init",
		},
		{
			id: "tty",
			path: `${CONTAINER_PATH}.TTY`,
			key: "TTY",
			type: "boolean",
			title: "Allocate a pseudo-TTY",
			summary: "Attaches a pseudo-terminal to the container.",
			details: [
				"Rarely wanted for a service. It changes how some runtimes buffer stdout, which can make logs appear line-buffered rather than block-buffered.",
			],
			cli: "docker service update --tty",
			compose: "services.<key>.tty",
		},
		{
			id: "open-stdin",
			path: `${CONTAINER_PATH}.OpenStdin`,
			key: "OpenStdin",
			type: "boolean",
			title: "Keep stdin open",
			summary: "Keeps the container's stdin open.",
			details: [
				"Only useful for interactive or REPL-style workloads; long-running servers should leave it off.",
			],
			cli: "docker service update --stdin-open",
			compose: "services.<key>.stdin_open",
		},
		{
			id: "cap-add",
			path: `${CONTAINER_PATH}.CapabilityAdd`,
			key: "CapabilityAdd",
			type: "lines",
			title: "Capabilities to add",
			summary: "Linux capabilities granted on top of the default set.",
			details: [
				"Use the full `CAP_` name, e.g. `CAP_NET_BIND_SERVICE` to bind ports below 1024 as a non-root user.",
				"Available from API v1.41 onwards.",
			],
			placeholder: "CAP_NET_BIND_SERVICE",
			cli: "docker service update --cap-add CAP_NET_BIND_SERVICE",
			compose: "services.<key>.cap_add",
		},
		{
			id: "cap-drop",
			path: `${CONTAINER_PATH}.CapabilityDrop`,
			key: "CapabilityDrop",
			type: "lines",
			title: "Capabilities to drop",
			summary: "Linux capabilities removed from the default set.",
			details: [
				"`CAP_ALL` drops everything, after which you add back only what the process needs. That deny-by-default posture is what auditors look for.",
			],
			placeholder: "CAP_ALL",
			cli: "docker service update --cap-drop CAP_ALL",
			compose: "services.<key>.cap_drop",
		},
		{
			id: "sysctls",
			path: `${CONTAINER_PATH}.Sysctls`,
			key: "Sysctls",
			type: "mapLines",
			title: "Sysctls",
			summary: "Namespaced kernel parameters set inside the container.",
			details: [
				"Only namespaced sysctls work — `net.core.somaxconn` yes, `net.ipv4.tcp_tw_reuse` no (that one is host-wide and must be set on the node).",
				"Swarm performs no validation here; a bad key fails at task start with a cryptic OCI runtime error.",
			],
			placeholder: "net.core.somaxconn=1024",
			cli: "docker service update --sysctl-add net.core.somaxconn=1024",
			compose: "services.<key>.sysctls",
			lineHint: "kv",
		},
		{
			id: "ulimits",
			path: `${CONTAINER_PATH}.Ulimits`,
			key: "Ulimits",
			type: "rows",
			title: "Ulimits",
			summary:
				"Per-process resource limits, e.g. the open file descriptor cap.",
			details: [
				"`nofile` is the one that matters for high-concurrency servers: the kernel default of 1024 will silently cap your connection count.",
				"Soft is the enforced value, hard is the ceiling the process may raise itself to.",
			],
			columns: [
				{
					key: "Name",
					label: "Name",
					type: "text",
					placeholder: "nofile",
					hint: "Limit name without the RLIMIT_ prefix, e.g. nofile, nproc, core.",
				},
				{
					key: "Soft",
					label: "Soft",
					type: "number",
					placeholder: "65536",
					width: "md",
					hint: "The value actually enforced at start.",
				},
				{
					key: "Hard",
					label: "Hard",
					type: "number",
					placeholder: "65536",
					width: "md",
					hint: "The maximum the process may raise the soft limit to.",
				},
			],
			cli: "docker service update --ulimit nofile=65536:65536",
			compose: "services.<key>.ulimits",
		},
		{
			id: "isolation",
			path: `${CONTAINER_PATH}.Isolation`,
			key: "Isolation",
			type: "select",
			title: "Isolation (Windows only)",
			summary: "Isolation technology used by Windows containers.",
			details: [
				"Ignored on Linux nodes. `hyperv` gives each container its own kernel at the cost of start-up latency.",
			],
			options: [
				{
					value: "default",
					label: "default",
					hint: "Whatever the daemon is configured to use.",
				},
				{
					value: "process",
					label: "process",
					hint: "Shared kernel; faster, Windows Server only.",
				},
				{
					value: "hyperv",
					label: "hyperv",
					hint: "Hyper-V isolated; stronger boundary, slower start.",
				},
			],
			cli: "docker service update --isolation hyperv",
			compose: "services.<key>.isolation",
		},
	],
};

export const healthSection: SectionDef = {
	id: "health",
	title: "Health check",
	path: `${CONTAINER_PATH}.HealthCheck`,
	summary:
		"The probe Swarm uses to decide whether a task is healthy — and therefore whether a rollout may continue.",
	details: [
		"Health checks are what make a rolling update safe. Without one, Swarm considers a task successful as soon as the process starts, so a container that boots and then crash-loops still counts as a good replica for `UpdateConfig.Monitor`.",
		"Every duration here is nanoseconds and must be 0 (inherit from the image) or at least 1 ms.",
	],
	fields: [
		{
			id: "health-test",
			path: `${CONTAINER_PATH}.HealthCheck.Test`,
			key: "Test",
			type: "lines",
			title: "Test",
			summary: "The probe command, one argv element per line.",
			details: [
				"The first line is the mode: `CMD` execs the remaining lines directly, `CMD-SHELL` runs a single following line through the image's shell, and `NONE` disables an inherited health check entirely.",
				"An empty array means 'inherit from the image'. Exit code 0 is healthy, 1 is unhealthy, anything else is an error.",
			],
			placeholder:
				"CMD-SHELL\ncurl -fsS http://localhost:8080/healthz || exit 1",
			cli: "docker service update --health-cmd 'curl -fsS http://localhost:8080/healthz'",
			compose: "services.<key>.healthcheck.test",
		},
		{
			id: "health-interval",
			path: `${CONTAINER_PATH}.HealthCheck.Interval`,
			key: "Interval",
			type: "duration",
			title: "Interval",
			summary: "Time between two probes.",
			details: [
				"Shorter intervals detect failures faster but multiply probe load across every replica. 5–10 s is a common compromise.",
			],
			defaultUnit: "s",
			placeholder: "10",
			cli: "docker service update --health-interval 10s",
			compose: "services.<key>.healthcheck.interval",
		},
		{
			id: "health-timeout",
			path: `${CONTAINER_PATH}.HealthCheck.Timeout`,
			key: "Timeout",
			type: "duration",
			title: "Timeout",
			summary: "How long a single probe may take before it counts as failed.",
			details: [
				"When the probe exceeds this it is killed without a graceful shutdown and recorded as a failure. Keep it well below `Interval`, otherwise probes overlap.",
			],
			defaultUnit: "s",
			placeholder: "3",
			cli: "docker service update --health-timeout 3s",
			compose: "services.<key>.healthcheck.timeout",
		},
		{
			id: "health-retries",
			path: `${CONTAINER_PATH}.HealthCheck.Retries`,
			key: "Retries",
			type: "number",
			title: "Retries",
			summary:
				"Consecutive failures needed before the task is marked unhealthy.",
			details: [
				"Guards against a single flaky probe restarting a healthy task. 3 is the usual choice; 0 means inherit from the image.",
			],
			placeholder: "3",
			cli: "docker service update --health-retries 3",
			compose: "services.<key>.healthcheck.retries",
		},
		{
			id: "health-start-period",
			path: `${CONTAINER_PATH}.HealthCheck.StartPeriod`,
			key: "StartPeriod",
			type: "duration",
			title: "Start period",
			summary: "Warm-up window during which failing probes do not count.",
			details: [
				"This is the field people forget. A JVM or a service that runs migrations on boot needs tens of seconds before it can answer; without a start period the first probes fail, retries are exhausted and Swarm restarts the task in a loop.",
			],
			defaultUnit: "s",
			placeholder: "60",
			cli: "docker service update --health-start-period 60s",
			compose: "services.<key>.healthcheck.start_period",
		},
	],
};
