import type { SectionDef } from "../field-types";

const CONTAINER_PATH = "TaskTemplate.ContainerSpec";

export const storageSection: SectionDef = {
	id: "storage",
	title: "Mounts, secrets & configs",
	path: CONTAINER_PATH,
	summary:
		"Everything that appears inside the container's filesystem but does not come from the image.",
	details: [
		"All three lists are replaced wholesale on update. Sending a body without `Mounts` unmounts every volume the service had.",
		"Secrets and configs are delivered by the managers over TLS and land as files (under `/run/secrets/<name>` and `/<name>` by default). They are immutable — rotating one means creating a new object and pointing the service at it, which is itself a service update.",
	],
	fields: [
		{
			id: "mounts",
			path: `${CONTAINER_PATH}.Mounts`,
			key: "Mounts",
			type: "rows",
			title: "Mounts",
			summary: "Volumes, bind mounts and tmpfs attached to each task.",
			details: [
				"`volume` is the portable choice and works across nodes when backed by a cluster-aware driver. `bind` ties the service to a specific node's filesystem, so pair it with a placement constraint or the task will break the moment it is rescheduled.",
				"`tmpfs` is what makes a read-only root filesystem usable: mount one at /tmp and at any cache path.",
			],
			columns: [
				{
					key: "Type",
					label: "Type",
					type: "select",
					options: [
						{
							value: "volume",
							label: "volume",
							hint: "Named volume managed by a driver.",
						},
						{
							value: "bind",
							label: "bind",
							hint: "A host path; requires the path to exist on the node.",
						},
						{
							value: "tmpfs",
							label: "tmpfs",
							hint: "In-memory filesystem; Source must be empty.",
						},
						{ value: "npipe", label: "npipe", hint: "Windows named pipe." },
						{
							value: "cluster",
							label: "cluster",
							hint: "Swarm cluster volume (CSI).",
						},
					],
					width: "w-40",
					hint: "Which mount mechanism to use.",
				},
				{
					key: "Source",
					label: "Source",
					type: "text",
					placeholder: "app-data",
					hint: "Volume name or host path. Must be empty for tmpfs.",
				},
				{
					key: "Target",
					label: "Target",
					type: "text",
					placeholder: "/var/lib/app",
					hint: "Absolute path inside the container.",
				},
				{
					key: "ReadOnly",
					label: "Read-only",
					type: "boolean",
					width: "w-32",
					hint: "Mount without write access.",
				},
				{
					key: "BindOptions.Propagation",
					label: "Bind propagation",
					type: "select",
					options: [
						{
							value: "rprivate",
							label: "rprivate",
							hint: "Default. No propagation either way.",
						},
						{
							value: "private",
							label: "private",
							hint: "No propagation, non-recursive.",
						},
						{
							value: "rshared",
							label: "rshared",
							hint: "Propagates both ways, recursively.",
						},
						{ value: "shared", label: "shared", hint: "Propagates both ways." },
						{
							value: "rslave",
							label: "rslave",
							hint: "Host to container only, recursively.",
						},
						{ value: "slave", label: "slave", hint: "Host to container only." },
					],
					width: "w-40",
					hint: "Bind mounts only: how mount events propagate between host and container.",
				},
				{
					key: "VolumeOptions.DriverConfig.Name",
					label: "Volume driver",
					type: "text",
					placeholder: "local",
					hint: "Volume mounts only: the driver used to create the volume.",
				},
				{
					key: "TmpfsOptions.SizeBytes",
					label: "tmpfs size (bytes)",
					type: "number",
					placeholder: "67108864",
					hint: "tmpfs mounts only: maximum size in bytes. 64 MiB is 67108864.",
				},
			],
			cli: "docker service update --mount-add type=volume,source=app-data,target=/var/lib/app",
			compose: "services.<key>.volumes",
			caution:
				"A bind mount without a matching placement constraint is a time bomb: the task works until it is rescheduled onto a node that lacks the path.",
		},
		{
			id: "secrets",
			path: `${CONTAINER_PATH}.Secrets`,
			key: "Secrets",
			type: "rows",
			title: "Secrets",
			summary: "Swarm secrets exposed to the tasks as files.",
			details: [
				"The API references secrets by ID, not by name — `SecretName` is only carried along for display. Look the ID up with `GET /secrets` before building the body.",
				"`File.Mode` is decimal, not octal: mode 0444 is 292.",
			],
			columns: [
				{
					key: "SecretName",
					label: "Secret name",
					type: "text",
					placeholder: "db_password",
					hint: "Human-readable name, used for lookup and display only.",
				},
				{
					key: "SecretID",
					label: "Secret ID",
					type: "text",
					placeholder: "blt1owaxmitz71s9v5zh81zun",
					hint: "The ID the daemon actually resolves. Required.",
				},
				{
					key: "File.Name",
					label: "File name",
					type: "text",
					placeholder: "db_password",
					hint: "Filename inside /run/secrets in the container.",
				},
				{
					key: "File.UID",
					label: "UID",
					type: "text",
					placeholder: "0",
					width: "w-24",
					hint: "Owner uid of the mounted file.",
				},
				{
					key: "File.GID",
					label: "GID",
					type: "text",
					placeholder: "0",
					width: "w-24",
					hint: "Owner gid of the mounted file.",
				},
				{
					key: "File.Mode",
					label: "Mode (decimal)",
					type: "number",
					placeholder: "292",
					width: "w-36",
					hint: "File mode as a decimal integer. 0444 = 292, 0400 = 256.",
				},
			],
			cli: "docker service update --secret-add source=db_password,target=db_password",
			compose: "services.<key>.secrets",
		},
		{
			id: "configs",
			path: `${CONTAINER_PATH}.Configs`,
			key: "Configs",
			type: "rows",
			title: "Configs",
			summary: "Swarm configs mounted into the tasks as files.",
			details: [
				"Same delivery mechanism as secrets but without the tmpfs and the encryption at rest — meant for non-sensitive files such as nginx.conf.",
				"Because configs are immutable, the standard rotation is: create `nginx.conf.v2`, update the service to reference it, then remove the old object once the rollout succeeds.",
			],
			columns: [
				{
					key: "ConfigName",
					label: "Config name",
					type: "text",
					placeholder: "nginx.conf.v2",
					hint: "Human-readable name, used for lookup and display only.",
				},
				{
					key: "ConfigID",
					label: "Config ID",
					type: "text",
					placeholder: "b6b1ex0ny1jnitqou2rn6u0my",
					hint: "The ID the daemon actually resolves. Required.",
				},
				{
					key: "File.Name",
					label: "Target path",
					type: "text",
					placeholder: "/etc/nginx/nginx.conf",
					hint: "Where the file lands inside the container.",
				},
				{
					key: "File.UID",
					label: "UID",
					type: "text",
					placeholder: "0",
					width: "w-24",
					hint: "Owner uid of the mounted file.",
				},
				{
					key: "File.GID",
					label: "GID",
					type: "text",
					placeholder: "0",
					width: "w-24",
					hint: "Owner gid of the mounted file.",
				},
				{
					key: "File.Mode",
					label: "Mode (decimal)",
					type: "number",
					placeholder: "292",
					width: "w-36",
					hint: "File mode as a decimal integer. 0444 = 292.",
				},
			],
			cli: "docker service update --config-add source=nginx.conf.v2,target=/etc/nginx/nginx.conf",
			compose: "services.<key>.configs",
		},
	],
};
